kind: Deployment
apiVersion: apps/v1
metadata:
  name: apps-nfs-provisioner
  labels:
    name: apps-nfs-provisioner  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-nfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apps-nfs-provisioner
    spec:
      serviceAccountName: apps-nfs-provisioner
      containers:
        - name: apps-nfs-provisioner
          image: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0
          # image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: apps.io/nfs
            - name: NFS_SERVER
              value: NFS_IP
            - name: NFS_PATH
              value: NFS_FILEPATH
      volumes:
        - name: nfs-client-root
          nfs:
            server: NFS_IP
            path: NFS_FILEPATH
