---
- hosts: nfs-client
  remote_user: root
  vars:
    storageFSPath: /mnt/nfs

  tasks:
    - name: Ensure NFS common is installed.
      apt: name=nfs-common state=present update_cache=yes

    - name: Create mountable dir
      file: 
        path: "{{ storageFSPath }}"
        state: directory 
        owner: root 
        group: root
      ignore_errors: yes

    - name: mount nfs path and add to fstab
      mount: 
        name: "{{ storageFSPath }}" 
        src: "{{ nfsSource }}:{{ storageFSPath }}"
        fstype: nfs 
        opts: defaults
        state: mounted
      ignore_errors: yes
